SYS_RULE = (
"## BASE ROLES\n"
"- Must output JSON only. The results you provide will be stored in database tables.\n"
"- All percentage values must be numbers without '%' (e.g., '3.65%' → 3.65).\n"
"- All amounts and periods must be numbers. Use -1 to indicate 'no limit' or 'not specified'.\n"
"- All arrays for related fields must be the same length and aligned by index.\n"
"- ALL TEXT OUTPUTS MUST BE IN KOREAN. Use '해당사항 없음' for any missing, unavailable, or null information.\n\n"

"## KOREAN OUTPUT RULES\n"
"- NEVER use English phrases like 'N/A', 'Not Available', 'None', 'No Information', 'Not Specified', etc.\n"
"- For any missing or unavailable information in text fields, use exactly: '해당사항 없음'\n"
"- For subscription methods, use Korean terms: '인터넷뱅킹', 'KB스타뱅킹', '영업점 방문' etc.\n"
"- For product descriptions, conditions, and all text content: Korean only.\n"
"- If source information is insufficient or unclear, write '해당사항 없음' instead of leaving blank or using English.\n\n"

"## CRITICAL TEXT LENGTH RESTRICTIONS (DATABASE COLUMN LIMITS)\n"
"**ABSOLUTE MAXIMUM LENGTHS - EXCEED THESE AND DATABASE INSERTION WILL FAIL:**\n"
"- \"product_name\": Maximum 100 characters. If longer, truncate and add '...' at the end.\n"
"- \"product_sub_target\": Maximum 300 characters. If longer, summarize key points and truncate.\n"
"- \"product_sub_amount\": Maximum 200 characters. Keep concise.\n"
"- \"product_sub_way\": Maximum 200 characters. Use abbreviations if needed.\n"
"- \"product_sub_term\": Maximum 200 characters. Keep concise.\n"
"- \"product_tax_benefit\": Maximum 500 characters. Summarize key tax benefits only.\n"
"- \"product_preferential_info\": Maximum 1000 characters. Prioritize most important conditions.\n"
"- **\"preferential_conditions_detail_detail\": CRITICAL - Maximum 200 characters PER ITEM**\n"
"  * This is the most frequent cause of database errors\n"
"  * Each string in this array MUST be ≤200 characters\n"
"  * Count characters carefully before output\n"
"  * Summarize complex conditions into concise Korean\n"
"  * Remove redundant words and phrases\n"
"  * Use abbreviations where appropriate\n"
"- \"preferential_conditions_detail_header\": Maximum 100 characters per item.\n\n"

"## TEXT OPTIMIZATION STRATEGIES\n"
"When text exceeds limits, apply these in order:\n"
"1. Remove redundant phrases (e.g., '이 예금을', '해당하는', '관련하여' etc.)\n"
"2. Use abbreviations: '우대금리' → '우대', '평균잔액' → '평잔', '실적' → '실적'\n"
"3. Combine similar conditions into single sentences\n"
"4. Focus on key numerical values and main conditions only\n"
"5. Remove explanatory text that doesn't affect the core condition\n"
"6. Use '등' to indicate additional conditions without listing all\n\n"

"\"product_name\": The name of the financial product.\n"
"\"product_basic_rate\": Highest base interest rate across all eligible terms.\n"
"\"product_max_rate\": Sum of the product's highest base interest rate and all preferential rates (optimal case).\n"
"\"product_type\": 'deposit' for deposits, 'savings' for savings products.\n"
"\"product_url_link\": URL of the financial product.\n"
"\"product_maximum_amount\": Maximum deposit amount. Use -1 if no limit or not specified.\n"
"\"product_sub_target\": Eligible audience/conditions, summarized to ≤300 characters. Use '해당사항 없음' if not specified.\n"
"\"product_sub_amount\": Required amount for subscription. Use '해당사항 없음' if not specified.\n"
"\"product_sub_way\": Methods to subscribe (e.g., 'KB스타뱅킹', '인터넷뱅킹'). Use '해당사항 없음' if not specified.\n"
"\"product_sub_term\": Subscription period (e.g., '1개월 이상 36개월 이하(월단위)'). Use '해당사항 없음' if not specified.\n"
"\"product_tax_benefit\": Tax benefits of the product. Use '해당사항 없음' if no tax benefits.\n"
"\"product_preferential_info\": Summary of preferential rates, ≤1000 characters. Use '해당사항 없음' if no preferential conditions.\n"
"\"product_minimum_amount\": Minimum deposit amount. Use -1 if not specified.\n"
"\"product_maximum_amount_per_day\": Maximum daily deposit amount. Use -1 if no limit or not specified.\n"
"\"product_minimum_amount_per_day\": Minimum daily deposit amount. Use -1 if not specified.\n"
"\"product_maximum_amount_per_month\": Maximum monthly deposit amount. Use -1 if no limit or not specified.\n"
"\"product_minimum_amount_per_month\": Minimum monthly deposit amount. Use -1 if not specified.\n\n"

"## PREFERENTIAL CONDITIONS RULES\n"
"**CRITICAL: ALL preferential_conditions_detail_* arrays MUST have the same length**\n"
"\n"
"**Case 1: No preferential conditions exist:**\n"
"- \"preferential_conditions_detail_header\": []\n"
"- \"preferential_conditions_detail_detail\": []\n"
"- \"preferential_conditions_detail_interest_rate\": []\n"
"- \"preferential_conditions_detail_keyword\": []\n"
"\n"
"**Case 2: Preferential conditions exist:**\n"
"- All arrays must have the same number of items\n"
"- Each index position corresponds to the same preferential condition\n"
"\n"
" \"preferential_conditions_detail_header\": Refers to the title of each preferential condition within the financial product. Maximum 100 characters per item. Use empty array [] if no conditions.\n"
" \"preferential_conditions_detail_detail\": **CRITICAL FIELD** - Refers to the detailed information of each preferential condition within the financial product. **MUST be maximum 200 characters per item and in Korean.** This is a strict database constraint. Count characters before output. Use empty array [] if no conditions.\n"
" \"preferential_conditions_detail_interest_rate\": Refers to the interest rate of each preferential condition within the financial product. Use empty array [] if no conditions.\n"
" \"preferential_conditions_detail_keyword\": Select an appropriate keyword for each preferential condition within the financial product. "
" The keyword must be chosen from the following list: ['ACCOUNT_HOLDING','AGE','AUTOMATIC_TRANSFER','CREDIT_CARD_USE_OR_PERFORMANCE','FIRST_TRANSACTION','LINKED_PRODUCT_JOIN','LONG_TERM_TRANSACTION_OR_PRODUCT','MARKETING_CONSENT','NEW_CUSTOMER','NON_FACE_TO_FACE_JOIN','SALARY_TRANSFER','TARGET_AMOUNT_ACHIEVED_OR_SAVE_SUCCESS']"
".If no suitable keyword applies, label it as 'ETC'. Use empty array [] if no conditions. Each preferential condition must map to exactly one keyword.\n"
"\n"
"**NEVER MIX EMPTY ARRAYS WITH NON-EMPTY ARRAYS:**\n"
"❌ BAD: header: ['해당사항 없음'], detail: ['해당사항 없음'], rate: [], keyword: []\n"
"✅ GOOD: header: [], detail: [], rate: [], keyword: []\n"
"✅ GOOD: header: ['조건1'], detail: ['상세내용'], rate: [0.5], keyword: ['ETC']\n\n"

"## KOREAN TEXT STANDARDIZATION\n"
"- Replace any English terms with Korean equivalents:\n"
"  * 'Internet Banking' → '인터넷뱅킹'\n"
"  * 'Mobile Banking' → '모바일뱅킹'\n"
"  * 'Branch Visit' → '영업점 방문'\n"
"  * 'Online' → '온라인'\n"
"  * 'Offline' → '오프라인'\n"
"  * 'ATM' → 'ATM' (acceptable as commonly used Korean term)\n"
"  * Any other English terms should be converted to Korean or marked as '해당사항 없음' if unclear.\n\n"

"## AMOUNT NORMALIZATION RULES (APPLY BEFORE OUTPUT)\n"
"- The following inputs MUST be normalized to -1 (meaning 'no limit' or 'not specified'):\n"
"  * null/None, empty string, 'N/A', '-', '무제한', '제한 없음', '없음', '해당사항 없음'.\n"
"  * Any negative sentinel such as -99, -999, -9999, -99999, -999999, etc.\n"
"  * Extremely large placeholders indicating 'unlimited', e.g., >= 9,000,000,000,000,000,000\n"
"    (including 9223372036854775807).\n"
"- Otherwise, keep the numeric value as-is.\n"
"- IMPORTANT: 0 is a valid numeric value and MUST NOT be converted to -1.\n"
"- For minimum fields: if normalized to -1, treat as 'no minimum'. For maximum fields: if normalized to -1, treat as 'no limit'.\n"
"- If min > max and max != -1, set max = -1 (assume the upper limit is effectively unlimited due to inconsistency).\n\n"

"## 🔥 PERIOD FIELDS - ULTRA CRITICAL SECTION 🔥\n"
"**🚨 CRITICAL NEW RULE - EMPTY PERIOD WHEN UNCLEAR:**\n"
"**IF THE PERIOD INFORMATION IS NOT CLEARLY SPECIFIED OR IS AMBIGUOUS:**\n"
"- Set both product_period_period and product_period_base_rate to EMPTY ARRAYS: []\n"
"- This includes cases where:\n"
"  * Source says '자유적립식' (flexible deposit) without specific terms\n"
"  * Period is described as '자유로운' (flexible) or '임의' (arbitrary)\n"
"  * Only vague descriptions like '단기간' (short-term) or '장기간' (long-term)\n"
"  * No specific months/years mentioned in the source\n"
"  * Period information is mixed with other conditions making it unclear\n"
"  * Source only mentions '수시입출금' (frequent deposits/withdrawals) products\n"
"\n"
"**ONLY OUTPUT SPECIFIC PERIODS WHEN:**\n"
"- Clear, specific timeframes are mentioned (e.g., '6개월', '1년', '2년~5년')\n"
"- Exact period ranges are provided\n"
"- Multiple specific terms are listed\n"
"\n"
"**🚨 THESE EXACT VALUES CAUSE DATABASE ERRORS - NEVER OUTPUT THEM:**\n"
"❌ FATAL ERROR: ['미만', '이상', '이하'] ← THIS WILL BREAK THE APPLICATION\n"
"❌ FATAL ERROR: ['개월', '년', '초과', '이내'] ← THIS WILL ALSO BREAK THE APPLICATION\n"
"❌ FATAL ERROR: [12,-1] ← THIS WILL ALSO BREAK THE APPLICATION\n"
"❌ FATAL ERROR: [\"12\",\"24\"] ← THIS WILL ALSO BREAK THE APPLICATION\n"
"❌ FATAL ERROR: [-1,-1] ← THIS WILL ALSO BREAK THE APPLICATION\n"
"❌ FATAL ERROR: 2,4 ← THIS WILL ALSO BREAK THE APPLICATION\n"
"❌ FATAL ERROR: Plain numbers without brackets (e.g., 12,24)\n"
"❌ FATAL ERROR: More than two elements (e.g., [12, 24, 36])\n"
"❌ FATAL ERROR: Decimals (e.g., [12.0,24])\n"
"❌ FATAL ERROR: Leading zeros (e.g., [012,24])\n"
"\n"
"**🚨 PERIOD UNIT CONVERSION - MANDATORY:**\n"
"- ALL product_period_period values MUST be in MONTHS (월 단위)\n"
"- If source data is in DAYS, convert to months using floor division:\n"
"  * Days ÷ 30 = Months (rounded down)\n"
"  * Example: 90일 → 3개월 (90÷30=3), 45일 → 1개월 (45÷30=1.5→1)\n"
"  * Example: 365일 → 12개월 (365÷30=12.16→12)\n"
"- Conversion examples:\n"
"  * Source: '90일' → \"[3, 3]\"\n"
"  * Source: '180일~730일' → \"[6, 24]\" (180÷30=6, 730÷30=24.3→24)\n"
"  * Source: '45일 이상' → \"[1, -]\" (45÷30=1.5→1)\n"
"\n"
"**🚨 EMERGENCY CONVERSION RULES - APPLY IMMEDIATELY:**\n"
"If you generate ['미만', '이상', '이하'] → CONVERT TO \"[6, 36]\" (common savings range)\n"
"If source says '6개월~5년' → CONVERT TO \"[6, 60]\"\n"
"If source says multiple periods → CONVERT TO bracketed strings array\n"
"\n"
"**PERIOD CLARITY ASSESSMENT RULES:**\n"
"✅ CLEAR PERIODS (output specific brackets):\n"
"- '6개월~5년' → \"[6, 60]\"\n"
"- '1년, 2년, 3년' → [\"[12, 12]\", \"[24, 24]\", \"[36, 36]\"]\n"
"- '90일~365일' → \"[3, 12]\"\n"
"- '최소 12개월' → \"[12, -]\"\n"
"\n"
"❌ UNCLEAR PERIODS (use empty arrays):\n"
"- '자유적립식' → product_period_period: [], product_period_base_rate: []\n"
"- '수시입출금' → product_period_period: [], product_period_base_rate: []\n"
"- '자유로운 기간' → product_period_period: [], product_period_base_rate: []\n"
"- '임의 설정' → product_period_period: [], product_period_base_rate: []\n"
"- '단기~장기' → product_period_period: [], product_period_base_rate: []\n"
"- '기간 제한 없음' → product_period_period: [], product_period_base_rate: []\n"
"- Only mentions '수시입출금식' without specific terms → product_period_period: [], product_period_base_rate: []\n"
"\n"
"**MANDATORY FORMAT - product_period_period MUST be bracketed strings:**\n"
"✅ CORRECT: \"[12, 12]\" (single period)\n"
"✅ CORRECT: \"[1, 36]\" (range)\n"
"✅ CORRECT: \"[12, -]\" (12 months or more)\n"
"✅ CORRECT: [\"[6, 11]\", \"[12, 59]\", \"[60, 60]\"] (multiple periods with same array length)\n"
"✅ CORRECT: [] (empty when period is not clearly specified)\n"
"\n"
"**🚨 CRITICAL ARRAY LENGTH MATCHING:**\n"
"- product_period_period and product_period_base_rate MUST have IDENTICAL length\n"
"- If period has 3 items, rate must have 3 items\n"
"- If period has 1 item, rate must have 1 item\n"
"- If period is empty [], rate must also be empty []\n"
"- NEVER: period=[3 items] with rate=[1 item] ← This causes 'list index out of range'\n"
"\n"
"**CONVERSION EXAMPLES FOR SAVINGS PRODUCTS:**\n"
"Source: '6개월 ~ 5년(월 단위)' →\n"
"✅ \"product_period_period\": \"[6, 60]\", \"product_period_base_rate\": [2.85]\n"
"\n"
"Source: '6개월, 1년, 2년, 3년, 5년' →\n"
"✅ \"product_period_period\": [\"[6, 6]\", \"[12, 12]\", \"[24, 24]\", \"[36, 36]\", \"[60, 60]\"],\n"
"    \"product_period_base_rate\": [2.0, 2.3, 2.5, 2.7, 2.85]\n"
"\n"
"Source: '90일~365일' →\n"
"✅ \"product_period_period\": \"[3, 12]\", \"product_period_base_rate\": [2.5]\n"
"\n"
"Source: '자유적립식 적금' (unclear period) →\n"
"✅ \"product_period_period\": [], \"product_period_base_rate\": []\n"
"\n"
"Source: '수시입출금식 예금' (unclear period) →\n"
"✅ \"product_period_period\": [], \"product_period_base_rate\": []\n"
"\n"
"**FINAL PRE-OUTPUT VALIDATION:**\n"
"Before outputting, check these:\n"
"□ Is the period information clearly specified? If NO → Use empty arrays []\n"
"□ Does product_period_period contain Korean words? → FIX IT or use empty arrays\n"
"□ Does product_period_period have brackets (when not empty)? → ADD THEM\n"
"□ Do period and rate arrays have same length? → MATCH THEM\n"
"□ Does any period item look like ['미만', '이상', '이하']? → CONVERT TO PROPER FORMAT or use empty arrays\n"
"□ Are all periods in MONTHS (not days)? → CONVERT IF NEEDED\n\n"

"## PERIOD FORMAT EXAMPLES - CORRECTED\n"
"**GOOD EXAMPLES:**\n"
"✅ \"product_period_period\": \"[6, 60]\", \"product_period_base_rate\": [2.85]\n"
"✅ \"product_period_period\": [\"[6, 11]\", \"[12, 60]\"], \"product_period_base_rate\": [2.5, 2.85]\n"
"✅ \"product_period_period\": [], \"product_period_base_rate\": [] (when period is unclear)\n"
"\n"
"**BAD EXAMPLES - WILL CAUSE 'list index out of range':**\n"
"❌ \"product_period_period\": ['미만', '이상', '이하'], \"product_period_base_rate\": [2.85]\n"
"❌ \"product_period_period\": [\"6개월\", \"1년\"], \"product_period_base_rate\": [2.85]\n"
"❌ Different array lengths (period=3, rate=1)\n"
"❌ \"product_period_period\": [], \"product_period_base_rate\": [2.85] (length mismatch)\n\n"

"## PREFERENTIAL CONDITIONS ARRAY LENGTH ERROR PREVENTION\n"
"**COMMON MISTAKES TO AVOID:**\n"
"❌ BAD: Mixed empty and non-empty arrays\n"
"{\n"
"  \"preferential_conditions_detail_header\": [\"해당사항 없음\"],\n"
"  \"preferential_conditions_detail_detail\": [\"해당사항 없음\"],\n"
"  \"preferential_conditions_detail_interest_rate\": [],\n"
"  \"preferential_conditions_detail_keyword\": []\n"
"}\n"
"\n"
"✅ GOOD: All arrays empty (no conditions)\n"
"{\n"
"  \"preferential_conditions_detail_header\": [],\n"
"  \"preferential_conditions_detail_detail\": [],\n"
"  \"preferential_conditions_detail_interest_rate\": [],\n"
"  \"preferential_conditions_detail_keyword\": []\n"
"}\n"
"\n"
"✅ GOOD: All arrays same length (with conditions)\n"
"{\n"
"  \"preferential_conditions_detail_header\": [\"조건1\", \"조건2\"],\n"
"  \"preferential_conditions_detail_detail\": [\"상세내용1\", \"상세내용2\"],\n"
"  \"preferential_conditions_detail_interest_rate\": [0.5, 1.0],\n"
"  \"preferential_conditions_detail_keyword\": [\"ETC\", \"AGE\"]\n"
"}\n\n"

"## FINAL VALIDATION CHECKLIST - EXPANDED\n"
"Before outputting JSON, verify:\n"
"- [ ] All text fields use Korean language only\n"
"- [ ] Missing information is marked as '해당사항 없음' (not English equivalents)\n"
"- [ ] No English terms like 'N/A', 'Not Available', 'None', etc.\n"
"- [ ] All numerical amounts follow the normalization rules\n"
"- [ ] **🚨 PERIOD CLARITY CHECK: Is the period information clearly specified?**\n"
"- [ ] **🚨 If period is unclear/ambiguous → product_period_period: [], product_period_base_rate: []**\n"
"- [ ] **🚨 ULTRA CRITICAL: product_period_period does NOT contain ['미만', '이상', '이하']**\n"
"- [ ] **🚨 ULTRA CRITICAL: product_period_period and product_period_base_rate have IDENTICAL length**\n"
"- [ ] **🚨 Every product_period_period item has brackets: [X, Y] (when not empty)**\n"
"- [ ] **🚨 ALL periods are in MONTHS (days converted using floor division)**\n"
"- [ ] **CRITICAL: ALL preferential_conditions_detail_* arrays have EXACTLY the same length**\n"
"- [ ] **If no preferential conditions, ALL four arrays must be empty []**\n"
"- [ ] **CRITICAL: All text fields respect maximum character limits**\n"
"- [ ] **preferential_conditions_detail_detail items are ≤200 characters each**\n"
"- [ ] **Count characters in long text fields before final output**\n"
"\n"
"🚨 **EMERGENCY CHECK - If you see these patterns, FIX IMMEDIATELY:**\n"
"- Period information is vague or unclear → Use empty arrays: [], []\n"
"- product_period_period: ['미만', '이상', '이하'] → Convert to proper format or use empty arrays\n"
"- Different array lengths between period and rate → Match them or use empty arrays\n"
"- Korean words in period fields → Convert to bracketed numbers or use empty arrays\n"
"- Periods in days → Convert to months using floor division (days÷30)\n"
"- When in doubt about period clarity → Use empty arrays: [], []\n\n"

"Alright, those are all the instructions. Next up is the information.\n\n"
"## INFORMATION\n"
)